### ISSUE TITLE
Can't import the named export 'diff' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by anujsinghwd** [uber/nebula.gl#285]
![screencapture-localhost-3000-2019-09-30-10_47_32](https://user-images.githubusercontent.com/24680004/65851221-c5bec680-e36f-11e9-86b5-eb9a4be2a73d.png)

**Comment by zoenberger** [comment]
Hi I saw this issue also. I don't quite know how to properly fix it, but per [this comment](https://github.com/Turfjs/turf/issues/1383#issuecomment-386627912) on a similar issue, I got past issue by doing the same super hacky workaround:

1. Open node_modules folder @turf/difference
2. Delete index.mjs
3. Recompile

Should at least get you going for now.

**Comment by kaseymccurdy** [comment]
We use Next.js, and we put this on our config to fix the issue:

```
const mjsConfig = (nextConfig = {}) => Object.assign({}, nextConfig, {
  // eslint-disable-next-line no-unused-vars
  webpack(config, options) {
    config.module.rules.push(
      {
        type: 'javascript/auto',
        test: /\.mjs$/,
        use: [],
      },
    );

    if (typeof nextConfig.webpack === 'function') {
      return nextConfig.webpack(config, options);
    }

    return config;
  },
});

module.exports = mjsConfig;
```

**Comment by xintongxia** [comment]
this is turf issue, https://github.com/Turfjs/turf/issues/1383#issuecomment-434486339

you can specify `resolutions` field in your app's package.json


```
  "resolutions": {
    "@turf/difference": "6.0.1"
  },
```

**Comment by anujsinghwd** [comment]
these all above solutions are not working still got the same error

**Comment by lerenah** [comment]
Same here

**Comment by wrdaigle** [comment]
> this is turf issue, [Turfjs/turf#1383 (comment)](https://github.com/Turfjs/turf/issues/1383#issuecomment-434486339)
> 
> you can specify `resolutions` field in your app's package.json
> 
> ```
>   "resolutions": {
>     "@turf/difference": "6.0.1"
>   },
> ```

For those of you trying to get this to work using npm, "resolutions" only work in yarn.  You need [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions) to use it with npm.

**Comment by rtsao** [comment]
I created a PR to fix this upstream: https://github.com/Turfjs/turf/pull/1805

**Comment by georgios-uber** [comment]
> I created a PR to fix this upstream: [Turfjs/turf#1805](https://github.com/Turfjs/turf/pull/1805)

Thanks. In the meantime a workaround is to delete all mjs files. Try this bash command:
`find node_modules -name "*.mjs" | xargs rm`

**Comment by georgios-uber** [comment]
Seems like it is fixed now.

**Comment by AntwanSherif** [comment]
I still have the same issue in my next.js app

**Comment by supersonicclay** [comment]
Try downgrading some turf.js libraries. I don't think turf has fully fixed their issues.

**Comment by kjkurtz** [comment]
Same here, still an issue with my next.js app. If I use @georgios-uber's suggestion to delete the mjs file then it works fine, but I have to do that after every time I run an `yarn install`.

**Comment by haxzie** [comment]
For anyone else facing this issue follow the below steps.
Add a preinstall script and resolutions into your package.json
```
...
"scripts": {
    "preinstall": "npx npm-force-resolutions",
    ...
},
...
"resolutions": {
    "@turf/difference": "6.0.1"
}
```

Remove your `node_modules` folder and run `npm install`. You are good to go! :+1:

**Comment by hassanms** [comment]
I encountered this error when I installed 'react-map-gl-draw' in my application, the error statement made me realized that it is related to Turf.js. I was successful in solving this by following haxzie's advice.
